[env]
TERM = "xterm-256color"

[font]
normal = { family = "SpaceMono Nerd Font Mono" }
bold = { family = "SpaceMono Nerd Font Mono" }
italic = { family = "SpaceMono Nerd Font Mono" }
size = 10

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[window]
padding.x = 7
padding.y = 5
dynamic_padding = true
decorations = "None"

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" }
]

[cursor]
thickness = 0.20

[colors.primary]
foreground = "#A7AFB9"
background = "#1e2229"
# background = "#212428"
# background = "#222327"
dim_foreground = "#5c6370"
bright_foreground = "#c8ccd4"

[colors.cursor]
text = "#282c34"
cursor = "#A7AFB9"

[colors.vi_mode_cursor]
text = "#282c34"
cursor = "#61afef"

[colors.search.matches]
foreground = "#abb2bf"
background = "#3e4451"

[colors.search.focused_match]
foreground = "#282c34"
background = "#e5c07b"

[colors.hints.start]
foreground = "#abb2bf"
background = "#3e4451"

[colors.hints.end]
foreground = "#c8ccd4"
background = "#3e4451"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#abb2bf"
background = "#21252b"

[colors.selection]
text = "#abb2bf"
background = "#3e4451"

[colors.normal]
black   = "#282c34"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#abb2bf"

[colors.bright]
black   = "#5c6370"
red     = "#e06c75"   # Some variants use #be5046
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#c8ccd4"

[colors.dim]
black   = "#21252b"
red     = "#be5046"
green   = "#7da869"
yellow  = "#d19a66"
blue    = "#528bff"
magenta = "#a678dd"
cyan    = "#4aa5b7"
white   = "#9aa2ad"
