# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="${FG_ACCENT}"

# Title color for boxes
theme[title]="${FG_ACCENT}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="${BLUE}"

# Background color of selected item in processes box
theme[selected_bg]="${BG_DARK}"

# Foreground color of selected item in processes box
theme[selected_fg]="${FG_ACCENT}"

# Color of inactive/disabled text
theme[inactive_fg]="${INACTIVE}"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="${PROC_MISC}"

# Cpu box outline color
theme[cpu_box]="${SURFACE}"

# Memory/disks box outline color
theme[mem_box]="${SURFACE}"

# Net up/down box outline color
theme[net_box]="${SURFACE}"

# Processes box outline color
theme[proc_box]="${SURFACE}"

# Box divider line and small boxes line color
theme[div_line]="${SURFACE}"

# Temperature graph colors
theme[temp_start]="${GREEN}"
theme[temp_mid]="${YELLOW}"
theme[temp_end]="${RED}"

# CPU graph colors
theme[cpu_start]="${GREEN}"
theme[cpu_mid]="${YELLOW}"
theme[cpu_end]="${RED}"

# Mem/Disk free meter
theme[free_start]="${CYAN}"
theme[free_mid]=""
theme[free_end]="${RED}"

# Mem/Disk cached meter
theme[cached_start]="${CYAN}"
theme[cached_mid]=""
theme[cached_end]="${RED}"

# Mem/Disk available meter
theme[available_start]="${CYAN}"
theme[available_mid]=""
theme[available_end]="${RED}"

# Mem/Disk used meter
theme[used_start]="${CYAN}"
theme[used_mid]=""
theme[used_end]="${RED}"

# Download graph colors
theme[download_start]="${GREEN}"
theme[download_mid]="${YELLOW}"
theme[download_end]="${RED}"

# Upload graph colors
theme[upload_start]="${GREEN}"
theme[upload_mid]="${YELLOW}"
theme[upload_end]="${RED}"
