[main]
font=SpaceMono Nerd Font Mono:size=12
prompt="System... "
width=32
lines=5

horizontal-pad=24
vertical-pad=20
inner-pad=6

[colors]
background=24932ff
text=cfd8dcff
prompt=4fa3ffff
#placeholder=6c7086ff
input=cfd8dcff
match=4fa3ffff

selection=2f3640ff
selection-text=4fa3ffff

border=89b4faff

[border]
width=2
radius=0
