[main]
font=SpaceMono Nerd Font Mono:size=14
prompt=""
width=32
lines=5
prev-with-wrap=Up
next-with-wrap=Down

keyboard-focus=exclusive
placeholder=Go…

horizontal-pad=30
vertical-pad=20
inner-pad=10
line-height=70px

[colors]
background=2f364010
text=cfd8dcff
prompt=4fa3ffff
#placeholder=6c7086ff
input=cfd8dcff
match=4fa3ffff

selection=2f3640ff
selection-text=4fa3ffff

border=89b4faff

[border]
width=2
radius=0
