[main]
font=SpaceMono Nerd Font Mono:size=14.5
prompt=""
width=18
minimal-lines=yes

keyboard-focus=exclusive
placeholder=Go…

horizontal-pad=30
vertical-pad=30
inner-pad=10
line-height=70px

[colors]
background=000000a2
text=cfd8dcff
prompt=4fa3ffff
#placeholder=6c7086ff
input=cfd8dcff
match=4fa3ffff

selection=2f364000
selection-text=56b6c2ff

border=0f0f0ff2

[border]
width=1
radius=4

[key-bindings]
prev=none
next=none
prev-with-wrap=Up
next-with-wrap=Down
