# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#c5c8c6"

# Title color for boxes
theme[title]="#c5c8c6"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#61afef"

# Background color of selected item in processes box
theme[selected_bg]="#282a2e"

# Foreground color of selected item in processes box
theme[selected_fg]="#c5c8c6"

# Color of inactive/disabled text
theme[inactive_fg]="#373b41"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#969896"

# Cpu box outline color
theme[cpu_box]="#3e4451"

# Memory/disks box outline color
theme[mem_box]="#3e4451"

# Net up/down box outline color
theme[net_box]="#3e4451"

# Processes box outline color
theme[proc_box]="#3e4451"

# Box divider line and small boxes line color
theme[div_line]="#3e4451"

# Temperature graph colors
theme[temp_start]="#98c379"
theme[temp_mid]="#e5c07b"
theme[temp_end]="#e06c75"

# CPU graph colors
theme[cpu_start]="#98c379"
theme[cpu_mid]="#e5c07b"
theme[cpu_end]="#e06c75"

# Mem/Disk free meter
theme[free_start]="#56b6c2"
theme[free_mid]=""
theme[free_end]="#e06c75"

# Mem/Disk cached meter
theme[cached_start]="#56b6c2"
theme[cached_mid]=""
theme[cached_end]="#e06c75"

# Mem/Disk available meter
theme[available_start]="#56b6c2"
theme[available_mid]=""
theme[available_end]="#e06c75"

# Mem/Disk used meter
theme[used_start]="#56b6c2"
theme[used_mid]=""
theme[used_end]="#e06c75"

# Download graph colors
theme[download_start]="#98c379"
theme[download_mid]="#e5c07b"
theme[download_end]="#e06c75"

# Upload graph colors
theme[upload_start]="#98c379"
theme[upload_mid]="#e5c07b"
theme[upload_end]="#e06c75"
