# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#a1aab7"

# Title color for boxes
theme[title]="#c9cfda"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#6e99c3"

# Background color of selected item in processes box
theme[selected_bg]="#2c3540"

# Foreground color of selected item in processes box
theme[selected_fg]="#c9cfda"

# Color of inactive/disabled text
theme[inactive_fg]="#5c6370"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#79838f"

# Cpu box outline color
theme[cpu_box]="#3f4751"

# Memory/disks box outline color
theme[mem_box]="#3f4751"

# Net up/down box outline color
theme[net_box]="#3f4751"

# Processes box outline color
theme[proc_box]="#3f4751"

# Box divider line and small boxes line color
theme[div_line]="#3f4751"

# Temperature graph colors
theme[temp_start]="#99bc76"
theme[temp_mid]="#d9a86c"
theme[temp_end]="#d77c73"

# CPU graph colors
theme[cpu_start]="#99bc76"
theme[cpu_mid]="#d9a86c"
theme[cpu_end]="#d77c73"

# Mem/Disk free meter
theme[free_start]="#70b6b9"
theme[free_mid]=""
theme[free_end]="#d77c73"

# Mem/Disk cached meter
theme[cached_start]="#70b6b9"
theme[cached_mid]=""
theme[cached_end]="#d77c73"

# Mem/Disk available meter
theme[available_start]="#70b6b9"
theme[available_mid]=""
theme[available_end]="#d77c73"

# Mem/Disk used meter
theme[used_start]="#70b6b9"
theme[used_mid]=""
theme[used_end]="#d77c73"

# Download graph colors
theme[download_start]="#99bc76"
theme[download_mid]="#d9a86c"
theme[download_end]="#d77c73"

# Upload graph colors
theme[upload_start]="#99bc76"
theme[upload_mid]="#d9a86c"
theme[upload_end]="#d77c73"
