# Prefix
set -g prefix M-a
unbind C-b
bind M-a send-prefix

# General
set -g mouse on
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Faster ESC for vim
set -sg escape-time 0

# forward focus events so nvim's FocusGained checktime fires
set -g focus-events on

# Window navigation
bind -r C-h previous-window
bind -r C-l next-window

# Jump to window by number
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Last session
bind -n M-j switch-client -l

# Copy mode
setw -g mode-keys vi
set -g status-keys vi

# Copy selection
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Jumps
bind -T copy-mode-vi C-u send -X halfpage-up
bind -T copy-mode-vi C-d send -X halfpage-down

# Status bar
set -g status-interval 5
set -g status-left-length 40
set -g status-right-length 80

set -g status-style bg=default
set -g status-left "#[fg=colour244] #S "
set -g status-right ""

# Window list
set -g window-status-format "#[fg=colour244] #I #W "
set -g window-status-current-format "#[fg=white,bold] #I #W "
set -g window-status-separator ""

# Reload config
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Sessionizer
bind f run-shell "tmux neww tmux-sessionizer"
