# Menus
bindd = SUPER, SPACE, Launch apps, exec, omarchy-launch-walker
bindd = SUPER ALT, SPACE, Omarchy menu, exec, omarchy-menu
bindd = SUPER, ESCAPE, System menu, exec, omarchy-menu system

# Captures
bindd = SUPER, P, Screenshot of region to clipboard, exec, omarchy-cmd-screenshot smart clipboard
bindd = SUPER SHIFT, P, Screenshot of display, exec, omarchy-cmd-screenshot output
bindd = SUPER CTRL, P, Screenshot of window, exec, omarchy-cmd-screenshot window
#bindd = SUPER, V, Screen record a region, exec, omarchy-cmd-screenrecord
#bindd = SUPER SHIFT, V, Screen record window, exec, omarchy-cmd-screenrecord window

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications"
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Toggle idling
bindd = SUPER CTRL, I, Toggle locking on idle, exec, coffee-toggle-idle
#bindd = SUPER CTRL, I, Toggle locking on idle, exec, omarchy-toggle-idle

# Nightlight
bindd = SUPER CTRL, N, Toggle nightlight, exec, omarchy-toggle-nightlight

# Lock screen
bindd = SUPER SHIFT, Q, Lock Screen, exec, omarchy-lock-screen

# Scratchpad
bindd = SUPER, S, Toggle scratchpad, togglespecialworkspace, scratchpad
bindd = SUPER SHIFT, S, Move window to scratchpad, movetoworkspacesilent, special:scratchpad
