# Background color
$color = rgba(40, 44, 52, 1.0)

# Inner overlay color
$inner_color = rgba(0, 0, 0, 0.4)

# Outer border/accent color
$outer_color = rgba(0, 0, 0, 0.9)

# Font color (main foreground)
$font_color = rgba(197, 200, 198, 1)

# Checkmark/success color (green accent)
$check_color = rgba(125, 168, 105, 1)

# Clock color
$clock_color = rgba(197, 200, 198, 1)

# Font
$font = InputMono Nerd Font

general {
  ignore_empty_input = true
}

background {
  monitor =
  color = $color
  path = ~/.config/coffee/background5.jpg
  blur_passes = 3
}

animations {
  enabled = false
}

label {
  monitor =
  text = $TIME
  font_size = 40
  color = $clock_color
  font_family = $font
  position = 0, 70
}

input-field {
  monitor =
  size = 270, 30
  position = 0, 0
  halign = center
  valign = center

  inner_color = $inner_color
  outer_color = $outer_color
  outline_thickness = 0

  font_family = $font
  font_color = $font_color

  dots_size = 0.2

  placeholder_text = Enter Password
  check_color = $check_color
  fail_color = rgba(190, 80, 70, 1)
  fail_text = <i>$FAIL ($ATTEMPTS)</i>

  rounding = 3
  shadow_passes = 0
  fade_on_empty = true
}

auth {
  fingerprint:enabled = true
}
