$color = rgba(0, 0, 0, 1.0)
$inner_color = rgba(0, 0, 0, 0.4)
$outer_color = rgba(112, 112, 112, 0.45)
$font_color = rgba(207, 216, 220, 1.0)
$check_color = rgba(125, 168, 105, 1.0)
$font = RobotoMono Nerd Font Mono, monospace

general {
  ignore_empty_input = true
}

background {
  monitor =
  color = $color
  path = ~/background.jpg
  blur_passes = 2
}

animations {
  enabled = false
}

# Clock and date on the left side.
label {
  monitor =
  text = cmd[update:1000] date +%H:%M
  font_size = 96
  font_family = $font
  color = $font_color
  position = 100, 35
  halign = left
  valign = center
}

label {
  monitor =
  text = cmd[update:60000] date +"%B %-d, %Y"
  font_size = 16
  color = $font_color
  font_family = $font
  position = 115, -65
  halign = left
  valign = center
}

# Power button in the upper-right corner.
# label {
#   monitor =
#   text = ⏻
#   font_size = 20
#   color = $font_color
#   font_family = $font
#   position = -40, -35
#   halign = right
#   valign = top
#   onclick = dot-cmd-shutdown
# }

input-field {
  monitor =
  size = 260, 35
  position = 0, 95
  halign = center
  valign = bottom

  inner_color = rgba(0, 0, 0, 0.0)
  outer_color = $outer_color
  outline_thickness = 1

  font_family = $font
  font_color = $font_color
  dots_size = 0.2
  placeholder_text = 
  check_color = $check_color
  fail_color = rgba(190, 80, 70, 1.0)
  fail_text = <i>$FAIL ($ATTEMPTS)</i>

  rounding = 6
  shadow_passes = 0
  fade_on_empty = true
}

auth {
  fingerprint:enabled = true
}
