# Extra autostart processes
# exec-once = uwsm-app -- my-service
# TODO-david
#exec-once = hyprpm reload
exec-once = [workspace 1] omarchy-launch-browser & omarchy-launch-or-focus signal-desktop & omarchy-launch-or-focus spotify
