# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
    #
    # TODO-david
    #layout = workspacelayout
}

# TODO-david
#plugin {
#    wslayout {
#        default_layout = dwindle
#    }
#}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    single_window_aspect_ratio = 1 1
}

master {
    orientation = center
    slave_count_for_center_master = 0
    always_keep_position = true
    mfact = 0.4
    new_on_top = 0
}
