"$schema" = 'https://starship.rs/config-schema.json'

format = """
$fill\
$line_break\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#c5c8c6"
truncation_length = 0
truncate_to_repo = false

[character]
success_symbol = "[∷](bright-black)"
error_symbol   = "[∷](red)"
vimcmd_symbol  = "[∷](green)"
# success_symbol = "[❯](bright-black)"
# error_symbol = "[❯](red)"
# vimcmd_symbol = "[❮](green)"

[fill]
symbol = "─"
style = "black"
# [╭](black)$fill[╮](black)\

[git_branch]
symbol = ""
format = "[$symbol $branch]($style)"
style = "bright-black"

[git_status]
format = " [$ahead_behind$stashed $all_status]($style) "
style = "green"

# Single-letter lowercase symbols for git status
conflicted = "c"
staged     = "s"
modified   = "m"
untracked  = "u"
renamed    = "r"
deleted    = "d"
stashed    = "p"
ahead      = "↑"
behind     = "↓"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "yellow"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
detect_extensions = []
detect_files = []
