[main]
term=xterm-256color
font=SpaceMono Nerd Font Mono:size=16
pad=5x0
bold-text-in-bright=no

[csd]
preferred=none

[colors-dark]
foreground=a1aab7
background=1b212a
cursor=1b212a a1aab7
regular0=12161c
regular1=d77c73
regular2=99bc76
regular3=d9a86c
regular4=6e99c3
regular5=b887c0
regular6=70b6b9
regular7=88929f

bright0=79838f
bright1=df9792
bright2=abcc8a
bright3=eac390
bright4=87aed6
bright5=c99dd2
bright6=86c8cc
bright7=c9cfda

selection-foreground=c9cfda
selection-background=3f4751
scrollback-indicator=88929f 191d24
search-box-match=12161c d9a86c
search-box-no-match=c9cfda 3f4751

[key-bindings]
# Replace Foot's default primary-selection paste on Shift+Insert.
primary-paste=none
clipboard-paste=Shift+Insert
clipboard-copy=Control+Insert
